// Generated by gencpp from file test_custom_msg/Student.msg
// DO NOT EDIT!


#ifndef TEST_CUSTOM_MSG_MESSAGE_STUDENT_H
#define TEST_CUSTOM_MSG_MESSAGE_STUDENT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_custom_msg
{
template <class ContainerAllocator>
struct Student_
{
  typedef Student_<ContainerAllocator> Type;

  Student_()
    : id()
    , name()
    , age(0)
    , gpa(0.0)  {
    }
  Student_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , name(_alloc)
    , age(0)
    , gpa(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef uint8_t _age_type;
  _age_type age;

   typedef float _gpa_type;
  _gpa_type gpa;





  typedef boost::shared_ptr< ::test_custom_msg::Student_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_custom_msg::Student_<ContainerAllocator> const> ConstPtr;

}; // struct Student_

typedef ::test_custom_msg::Student_<std::allocator<void> > Student;

typedef boost::shared_ptr< ::test_custom_msg::Student > StudentPtr;
typedef boost::shared_ptr< ::test_custom_msg::Student const> StudentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_custom_msg::Student_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_custom_msg::Student_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_custom_msg::Student_<ContainerAllocator1> & lhs, const ::test_custom_msg::Student_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.gpa == rhs.gpa;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_custom_msg::Student_<ContainerAllocator1> & lhs, const ::test_custom_msg::Student_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_custom_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test_custom_msg::Student_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_custom_msg::Student_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_custom_msg::Student_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_custom_msg::Student_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_custom_msg::Student_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_custom_msg::Student_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_custom_msg::Student_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24ce0792e01568f324298fd20a78d848";
  }

  static const char* value(const ::test_custom_msg::Student_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24ce0792e01568f3ULL;
  static const uint64_t static_value2 = 0x24298fd20a78d848ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_custom_msg::Student_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_custom_msg/Student";
  }

  static const char* value(const ::test_custom_msg::Student_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_custom_msg::Student_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n"
"string name\n"
"uint8 age\n"
"float32 gpa\n"
;
  }

  static const char* value(const ::test_custom_msg::Student_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_custom_msg::Student_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.gpa);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Student_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_custom_msg::Student_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_custom_msg::Student_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
    s << indent << "gpa: ";
    Printer<float>::stream(s, indent + "  ", v.gpa);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_CUSTOM_MSG_MESSAGE_STUDENT_H
