; Auto-generated. Do not edit!


(cl:in-package homework_ws-msg)


;//! \htmlinclude CounterGoal.msg.html

(cl:defclass <CounterGoal> (roslisp-msg-protocol:ros-message)
  ((num_counts
    :reader num_counts
    :initarg :num_counts
    :type cl:integer
    :initform 0))
)

(cl:defclass CounterGoal (<CounterGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CounterGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CounterGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name homework_ws-msg:<CounterGoal> is deprecated: use homework_ws-msg:CounterGoal instead.")))

(cl:ensure-generic-function 'num_counts-val :lambda-list '(m))
(cl:defmethod num_counts-val ((m <CounterGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader homework_ws-msg:num_counts-val is deprecated.  Use homework_ws-msg:num_counts instead.")
  (num_counts m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CounterGoal>) ostream)
  "Serializes a message object of type '<CounterGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'num_counts)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'num_counts)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'num_counts)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'num_counts)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CounterGoal>) istream)
  "Deserializes a message object of type '<CounterGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'num_counts)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'num_counts)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'num_counts)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'num_counts)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CounterGoal>)))
  "Returns string type for a message object of type '<CounterGoal>"
  "homework_ws/CounterGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CounterGoal)))
  "Returns string type for a message object of type 'CounterGoal"
  "homework_ws/CounterGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CounterGoal>)))
  "Returns md5sum for a message object of type '<CounterGoal>"
  "42f5ddfe2ee41298918bff5bf724cca8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CounterGoal)))
  "Returns md5sum for a message object of type 'CounterGoal"
  "42f5ddfe2ee41298918bff5bf724cca8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CounterGoal>)))
  "Returns full string definition for message of type '<CounterGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 num_counts~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CounterGoal)))
  "Returns full string definition for message of type 'CounterGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 num_counts~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CounterGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CounterGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CounterGoal
    (cl:cons ':num_counts (num_counts msg))
))
