; Auto-generated. Do not edit!


(cl:in-package homework_ws-msg)


;//! \htmlinclude CounterFeedback.msg.html

(cl:defclass <CounterFeedback> (roslisp-msg-protocol:ros-message)
  ((counts_elapsed
    :reader counts_elapsed
    :initarg :counts_elapsed
    :type cl:integer
    :initform 0))
)

(cl:defclass CounterFeedback (<CounterFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CounterFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CounterFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name homework_ws-msg:<CounterFeedback> is deprecated: use homework_ws-msg:CounterFeedback instead.")))

(cl:ensure-generic-function 'counts_elapsed-val :lambda-list '(m))
(cl:defmethod counts_elapsed-val ((m <CounterFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader homework_ws-msg:counts_elapsed-val is deprecated.  Use homework_ws-msg:counts_elapsed instead.")
  (counts_elapsed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CounterFeedback>) ostream)
  "Serializes a message object of type '<CounterFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'counts_elapsed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'counts_elapsed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'counts_elapsed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'counts_elapsed)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CounterFeedback>) istream)
  "Deserializes a message object of type '<CounterFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'counts_elapsed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'counts_elapsed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'counts_elapsed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'counts_elapsed)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CounterFeedback>)))
  "Returns string type for a message object of type '<CounterFeedback>"
  "homework_ws/CounterFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CounterFeedback)))
  "Returns string type for a message object of type 'CounterFeedback"
  "homework_ws/CounterFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CounterFeedback>)))
  "Returns md5sum for a message object of type '<CounterFeedback>"
  "cca3cfadafd90f6c2989b5f5e521eb59")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CounterFeedback)))
  "Returns md5sum for a message object of type 'CounterFeedback"
  "cca3cfadafd90f6c2989b5f5e521eb59")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CounterFeedback>)))
  "Returns full string definition for message of type '<CounterFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 counts_elapsed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CounterFeedback)))
  "Returns full string definition for message of type 'CounterFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 counts_elapsed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CounterFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CounterFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CounterFeedback
    (cl:cons ':counts_elapsed (counts_elapsed msg))
))
