// Generated by gencpp from file basic_test/Multiply.msg
// DO NOT EDIT!


#ifndef BASIC_TEST_MESSAGE_MULTIPLY_H
#define BASIC_TEST_MESSAGE_MULTIPLY_H

#include <ros/service_traits.h>


#include <basic_test/MultiplyRequest.h>
#include <basic_test/MultiplyResponse.h>


namespace basic_test
{

struct Multiply
{

typedef MultiplyRequest Request;
typedef MultiplyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Multiply
} // namespace basic_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::basic_test::Multiply > {
  static const char* value()
  {
    return "08c6eb99904d401fb2c8955af68adc03";
  }

  static const char* value(const ::basic_test::Multiply&) { return value(); }
};

template<>
struct DataType< ::basic_test::Multiply > {
  static const char* value()
  {
    return "basic_test/Multiply";
  }

  static const char* value(const ::basic_test::Multiply&) { return value(); }
};


// service_traits::MD5Sum< ::basic_test::MultiplyRequest> should match
// service_traits::MD5Sum< ::basic_test::Multiply >
template<>
struct MD5Sum< ::basic_test::MultiplyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::basic_test::Multiply >::value();
  }
  static const char* value(const ::basic_test::MultiplyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::basic_test::MultiplyRequest> should match
// service_traits::DataType< ::basic_test::Multiply >
template<>
struct DataType< ::basic_test::MultiplyRequest>
{
  static const char* value()
  {
    return DataType< ::basic_test::Multiply >::value();
  }
  static const char* value(const ::basic_test::MultiplyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::basic_test::MultiplyResponse> should match
// service_traits::MD5Sum< ::basic_test::Multiply >
template<>
struct MD5Sum< ::basic_test::MultiplyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::basic_test::Multiply >::value();
  }
  static const char* value(const ::basic_test::MultiplyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::basic_test::MultiplyResponse> should match
// service_traits::DataType< ::basic_test::Multiply >
template<>
struct DataType< ::basic_test::MultiplyResponse>
{
  static const char* value()
  {
    return DataType< ::basic_test::Multiply >::value();
  }
  static const char* value(const ::basic_test::MultiplyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASIC_TEST_MESSAGE_MULTIPLY_H
