// Generated by gencpp from file basic_test/MultiplyRequest.msg
// DO NOT EDIT!


#ifndef BASIC_TEST_MESSAGE_MULTIPLYREQUEST_H
#define BASIC_TEST_MESSAGE_MULTIPLYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace basic_test
{
template <class ContainerAllocator>
struct MultiplyRequest_
{
  typedef MultiplyRequest_<ContainerAllocator> Type;

  MultiplyRequest_()
    : num1(0)
    , num2(0)  {
    }
  MultiplyRequest_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)  {
  (void)_alloc;
    }



   typedef int16_t _num1_type;
  _num1_type num1;

   typedef int16_t _num2_type;
  _num2_type num2;





  typedef boost::shared_ptr< ::basic_test::MultiplyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::basic_test::MultiplyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MultiplyRequest_

typedef ::basic_test::MultiplyRequest_<std::allocator<void> > MultiplyRequest;

typedef boost::shared_ptr< ::basic_test::MultiplyRequest > MultiplyRequestPtr;
typedef boost::shared_ptr< ::basic_test::MultiplyRequest const> MultiplyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::basic_test::MultiplyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::basic_test::MultiplyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::basic_test::MultiplyRequest_<ContainerAllocator1> & lhs, const ::basic_test::MultiplyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1 &&
    lhs.num2 == rhs.num2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::basic_test::MultiplyRequest_<ContainerAllocator1> & lhs, const ::basic_test::MultiplyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace basic_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::basic_test::MultiplyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic_test::MultiplyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::basic_test::MultiplyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::basic_test::MultiplyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic_test::MultiplyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic_test::MultiplyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::basic_test::MultiplyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43f8a41a4ce6d514ef748e45b8dab7d9";
  }

  static const char* value(const ::basic_test::MultiplyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43f8a41a4ce6d514ULL;
  static const uint64_t static_value2 = 0xef748e45b8dab7d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::basic_test::MultiplyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "basic_test/MultiplyRequest";
  }

  static const char* value(const ::basic_test::MultiplyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::basic_test::MultiplyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 num1\n"
"int16 num2\n"
;
  }

  static const char* value(const ::basic_test::MultiplyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::basic_test::MultiplyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiplyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::basic_test::MultiplyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::basic_test::MultiplyRequest_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.num1);
    s << indent << "num2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.num2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASIC_TEST_MESSAGE_MULTIPLYREQUEST_H
