// Generated by gencpp from file test_ros_service/sampleServiceResponse.msg
// DO NOT EDIT!


#ifndef TEST_ROS_SERVICE_MESSAGE_SAMPLESERVICERESPONSE_H
#define TEST_ROS_SERVICE_MESSAGE_SAMPLESERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_ros_service
{
template <class ContainerAllocator>
struct sampleServiceResponse_
{
  typedef sampleServiceResponse_<ContainerAllocator> Type;

  sampleServiceResponse_()
    : turn()  {
    }
  sampleServiceResponse_(const ContainerAllocator& _alloc)
    : turn(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _turn_type;
  _turn_type turn;





  typedef boost::shared_ptr< ::test_ros_service::sampleServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_ros_service::sampleServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sampleServiceResponse_

typedef ::test_ros_service::sampleServiceResponse_<std::allocator<void> > sampleServiceResponse;

typedef boost::shared_ptr< ::test_ros_service::sampleServiceResponse > sampleServiceResponsePtr;
typedef boost::shared_ptr< ::test_ros_service::sampleServiceResponse const> sampleServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_ros_service::sampleServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_ros_service::sampleServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_ros_service::sampleServiceResponse_<ContainerAllocator1> & lhs, const ::test_ros_service::sampleServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.turn == rhs.turn;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_ros_service::sampleServiceResponse_<ContainerAllocator1> & lhs, const ::test_ros_service::sampleServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_ros_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test_ros_service::sampleServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_ros_service::sampleServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_ros_service::sampleServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_ros_service::sampleServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_ros_service::sampleServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_ros_service::sampleServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_ros_service::sampleServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "318653ac5e682e6ac5a91ab3fcbcfd51";
  }

  static const char* value(const ::test_ros_service::sampleServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x318653ac5e682e6aULL;
  static const uint64_t static_value2 = 0xc5a91ab3fcbcfd51ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_ros_service::sampleServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_ros_service/sampleServiceResponse";
  }

  static const char* value(const ::test_ros_service::sampleServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_ros_service::sampleServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string turn\n"
;
  }

  static const char* value(const ::test_ros_service::sampleServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_ros_service::sampleServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sampleServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_ros_service::sampleServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_ros_service::sampleServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "turn: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.turn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_ROS_SERVICE_MESSAGE_SAMPLESERVICERESPONSE_H
