// Generated by gencpp from file test_ros_service/sampleService.msg
// DO NOT EDIT!


#ifndef TEST_ROS_SERVICE_MESSAGE_SAMPLESERVICE_H
#define TEST_ROS_SERVICE_MESSAGE_SAMPLESERVICE_H

#include <ros/service_traits.h>


#include <test_ros_service/sampleServiceRequest.h>
#include <test_ros_service/sampleServiceResponse.h>


namespace test_ros_service
{

struct sampleService
{

typedef sampleServiceRequest Request;
typedef sampleServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sampleService
} // namespace test_ros_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_ros_service::sampleService > {
  static const char* value()
  {
    return "b59753b55c16f36d035056bfb3b80cf0";
  }

  static const char* value(const ::test_ros_service::sampleService&) { return value(); }
};

template<>
struct DataType< ::test_ros_service::sampleService > {
  static const char* value()
  {
    return "test_ros_service/sampleService";
  }

  static const char* value(const ::test_ros_service::sampleService&) { return value(); }
};


// service_traits::MD5Sum< ::test_ros_service::sampleServiceRequest> should match
// service_traits::MD5Sum< ::test_ros_service::sampleService >
template<>
struct MD5Sum< ::test_ros_service::sampleServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_ros_service::sampleService >::value();
  }
  static const char* value(const ::test_ros_service::sampleServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_ros_service::sampleServiceRequest> should match
// service_traits::DataType< ::test_ros_service::sampleService >
template<>
struct DataType< ::test_ros_service::sampleServiceRequest>
{
  static const char* value()
  {
    return DataType< ::test_ros_service::sampleService >::value();
  }
  static const char* value(const ::test_ros_service::sampleServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_ros_service::sampleServiceResponse> should match
// service_traits::MD5Sum< ::test_ros_service::sampleService >
template<>
struct MD5Sum< ::test_ros_service::sampleServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_ros_service::sampleService >::value();
  }
  static const char* value(const ::test_ros_service::sampleServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_ros_service::sampleServiceResponse> should match
// service_traits::DataType< ::test_ros_service::sampleService >
template<>
struct DataType< ::test_ros_service::sampleServiceResponse>
{
  static const char* value()
  {
    return DataType< ::test_ros_service::sampleService >::value();
  }
  static const char* value(const ::test_ros_service::sampleServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_ROS_SERVICE_MESSAGE_SAMPLESERVICE_H
