// Generated by gencpp from file homework_ws/CounterFeedback.msg
// DO NOT EDIT!


#ifndef HOMEWORK_WS_MESSAGE_COUNTERFEEDBACK_H
#define HOMEWORK_WS_MESSAGE_COUNTERFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace homework_ws
{
template <class ContainerAllocator>
struct CounterFeedback_
{
  typedef CounterFeedback_<ContainerAllocator> Type;

  CounterFeedback_()
    : counts_elapsed(0)  {
    }
  CounterFeedback_(const ContainerAllocator& _alloc)
    : counts_elapsed(0)  {
  (void)_alloc;
    }



   typedef uint32_t _counts_elapsed_type;
  _counts_elapsed_type counts_elapsed;





  typedef boost::shared_ptr< ::homework_ws::CounterFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::homework_ws::CounterFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CounterFeedback_

typedef ::homework_ws::CounterFeedback_<std::allocator<void> > CounterFeedback;

typedef boost::shared_ptr< ::homework_ws::CounterFeedback > CounterFeedbackPtr;
typedef boost::shared_ptr< ::homework_ws::CounterFeedback const> CounterFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::homework_ws::CounterFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::homework_ws::CounterFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::homework_ws::CounterFeedback_<ContainerAllocator1> & lhs, const ::homework_ws::CounterFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.counts_elapsed == rhs.counts_elapsed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::homework_ws::CounterFeedback_<ContainerAllocator1> & lhs, const ::homework_ws::CounterFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace homework_ws

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::homework_ws::CounterFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::homework_ws::CounterFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::homework_ws::CounterFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::homework_ws::CounterFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::homework_ws::CounterFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::homework_ws::CounterFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::homework_ws::CounterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cca3cfadafd90f6c2989b5f5e521eb59";
  }

  static const char* value(const ::homework_ws::CounterFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcca3cfadafd90f6cULL;
  static const uint64_t static_value2 = 0x2989b5f5e521eb59ULL;
};

template<class ContainerAllocator>
struct DataType< ::homework_ws::CounterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "homework_ws/CounterFeedback";
  }

  static const char* value(const ::homework_ws::CounterFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::homework_ws::CounterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint32 counts_elapsed\n"
;
  }

  static const char* value(const ::homework_ws::CounterFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::homework_ws::CounterFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.counts_elapsed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CounterFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::homework_ws::CounterFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::homework_ws::CounterFeedback_<ContainerAllocator>& v)
  {
    s << indent << "counts_elapsed: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.counts_elapsed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOMEWORK_WS_MESSAGE_COUNTERFEEDBACK_H
