// Generated by gencpp from file homework_ws/CounterResult.msg
// DO NOT EDIT!


#ifndef HOMEWORK_WS_MESSAGE_COUNTERRESULT_H
#define HOMEWORK_WS_MESSAGE_COUNTERRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace homework_ws
{
template <class ContainerAllocator>
struct CounterResult_
{
  typedef CounterResult_<ContainerAllocator> Type;

  CounterResult_()
    : result_message()  {
    }
  CounterResult_(const ContainerAllocator& _alloc)
    : result_message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_message_type;
  _result_message_type result_message;





  typedef boost::shared_ptr< ::homework_ws::CounterResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::homework_ws::CounterResult_<ContainerAllocator> const> ConstPtr;

}; // struct CounterResult_

typedef ::homework_ws::CounterResult_<std::allocator<void> > CounterResult;

typedef boost::shared_ptr< ::homework_ws::CounterResult > CounterResultPtr;
typedef boost::shared_ptr< ::homework_ws::CounterResult const> CounterResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::homework_ws::CounterResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::homework_ws::CounterResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::homework_ws::CounterResult_<ContainerAllocator1> & lhs, const ::homework_ws::CounterResult_<ContainerAllocator2> & rhs)
{
  return lhs.result_message == rhs.result_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::homework_ws::CounterResult_<ContainerAllocator1> & lhs, const ::homework_ws::CounterResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace homework_ws

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::homework_ws::CounterResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::homework_ws::CounterResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::homework_ws::CounterResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::homework_ws::CounterResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::homework_ws::CounterResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::homework_ws::CounterResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::homework_ws::CounterResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be8a5eb8699d93f379b287dcfc6e376c";
  }

  static const char* value(const ::homework_ws::CounterResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe8a5eb8699d93f3ULL;
  static const uint64_t static_value2 = 0x79b287dcfc6e376cULL;
};

template<class ContainerAllocator>
struct DataType< ::homework_ws::CounterResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "homework_ws/CounterResult";
  }

  static const char* value(const ::homework_ws::CounterResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::homework_ws::CounterResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string result_message\n"
;
  }

  static const char* value(const ::homework_ws::CounterResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::homework_ws::CounterResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CounterResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::homework_ws::CounterResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::homework_ws::CounterResult_<ContainerAllocator>& v)
  {
    s << indent << "result_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOMEWORK_WS_MESSAGE_COUNTERRESULT_H
